import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-gray-900 text-white mt-12">
      <div className="max-w-7xl mx-auto px-6 py-12">

        <div className="border-t border-gray-800 ">
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
            <h5 className="text-yellow-800 font-semibold mb-2">⚠️ Important Disclaimer</h5>
            <p className="text-yellow-700 text-sm leading-relaxed">
              <strong>Data Accuracy:</strong> All accessibility test results are generated by automated tools 
              and should be reviewed by qualified accessibility experts. Results may vary based on testing 
              conditions and tool configurations.
            </p>
            <p className="text-yellow-700 text-sm leading-relaxed mt-2">
              <strong>Compliance:</strong> Meeting WCAG guidelines requires both automated and manual testing. 
              These reports provide initial insights but do not guarantee full compliance with accessibility standards.
            </p>
            <p className="text-yellow-700 text-sm leading-relaxed mt-2">
              <strong>Usage:</strong> This dashboard is for internal use only. Do not share sensitive 
              accessibility data with unauthorized parties. Always follow your organization's data 
              handling policies.
            </p>
          </div>

          <div className="flex flex-col md:flex-row justify-between items-center">
            <p className="text-gray-400 text-sm">
              © 2024 TestYantra Global. All rights reserved.
            </p>
            <p className="text-gray-400 text-sm mt-2 md:mt-0">
              Firelink Accessibility Report System v2.1.0
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;